[package]
name = "goiaba"
version = "0.0.1"
edition = "2024"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-encoder = "0.228.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
wasmtime = "25.0.0"