[package]
name = "goiaba"
version = "0.0.2"
edition = "2024"
repository = "https://github.com/raphamorim/goiaba"
license = "GPL-3.0-or-later"
description = "Experimental Go parser and compiler"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-encoder = "0.239.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
wasmtime = "25.0.0"